// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tffhtsktcaskqhvpmwuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmZmh0c2t0Y2Fza3FodnBtd3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNzk3OTMsImV4cCI6MjA5MTY1NTc5M30.E5CV7vQ68lgu0CnTRqkn3rA8ymFHGS81Bw3C3Lr83qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});